package org.openjproxy.jdbc;

import com.openjproxy.grpc.DbName;
import com.openjproxy.grpc.OpQueryResultProto;
import com.openjproxy.grpc.OpResult;
import com.openjproxy.grpc.ResultType;
import com.openjproxy.grpc.SessionInfo;
import org.junit.jupiter.api.Test;

import java.util.Collections;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Regression tests for the {@code moreResultsExhausted} local cache and {@code resetMoreResultsState()}
 * introduced on {@link Statement} (see PR #585). Once the server reports that
 * {@link Statement#getMoreResults()} has no more results, that terminal state must be cached
 * locally to avoid a network round-trip on every redundant poll, and must be reset before the
 * next execution of the same {@link Statement}; otherwise a later query on a reused Statement
 * would be incorrectly short-circuited by a stale exhausted flag left over from a previous
 * execution.
 */
class StatementMoreResultsStateTest {

    // SessionInfo with an empty connHash so Connection#getThrottleManager() returns null and
    // client-side throttling is bypassed entirely for these unit tests.
    private static final SessionInfo SESSION = SessionInfo.newBuilder().setConnHash("").build();

    @Test
    void shouldCacheMoreResultsExhaustedLocallyAfterServerReturnsFalse() throws Exception {
        FakeStatementService fakeService = new FakeStatementService();
        Statement statement = new Statement(newConnection(fakeService), fakeService);
        fakeService.setCallResourceReturnValue(false);

        assertFalse(statement.getMoreResults());
        assertFalse(statement.getMoreResults());

        assertEquals(1, countMoreResultsInvocations(fakeService));
    }

    @Test
    void shouldNotCacheWhenServerStillHasMoreResults() throws Exception {
        FakeStatementService fakeService = new FakeStatementService();
        Statement statement = new Statement(newConnection(fakeService), fakeService);
        fakeService.setCallResourceReturnValue(true);

        assertTrue(statement.getMoreResults());
        assertTrue(statement.getMoreResults());

        assertEquals(2, countMoreResultsInvocations(fakeService));
    }

    @Test
    void shouldCacheMoreResultsExhaustedLocallyForOverloadWithCurrentParameter() throws Exception {
        FakeStatementService fakeService = new FakeStatementService();
        Statement statement = new Statement(newConnection(fakeService), fakeService);
        fakeService.setCallResourceReturnValue(false);

        assertFalse(statement.getMoreResults(java.sql.Statement.CLOSE_CURRENT_RESULT));
        assertFalse(statement.getMoreResults(java.sql.Statement.CLOSE_CURRENT_RESULT));

        assertEquals(1, countMoreResultsInvocations(fakeService));
    }

    @Test
    void shouldResetMoreResultsStateAfterExecuteUpdatePlain() throws Exception {
        FakeStatementService fakeService = new FakeStatementService(updateResult(1), null);
        Statement statement = new Statement(newConnection(fakeService), fakeService);
        exhaustMoreResults(statement, fakeService);

        statement.executeUpdate("UPDATE t SET x = 1");
        fakeService.setCallResourceReturnValue(false);
        statement.getMoreResults();

        assertEquals(2, countMoreResultsInvocations(fakeService));
    }

    @Test
    void shouldResetMoreResultsStateAfterExecuteQuery() throws Exception {
        FakeStatementService fakeService = new FakeStatementService(null, emptyQueryResult());
        Statement statement = new Statement(newConnection(fakeService), fakeService);
        exhaustMoreResults(statement, fakeService);

        statement.executeQuery("SELECT 1");
        fakeService.setCallResourceReturnValue(false);
        statement.getMoreResults();

        assertEquals(2, countMoreResultsInvocations(fakeService));
    }

    @Test
    void shouldResetMoreResultsStateAfterExecuteWithAutoGeneratedKeys() throws Exception {
        FakeStatementService fakeService = new FakeStatementService();
        Statement statement = new Statement(newConnection(fakeService), fakeService);
        exhaustMoreResults(statement, fakeService);

        fakeService.setCallResourceReturnValue(false);
        statement.execute("INSERT INTO t VALUES (1)", java.sql.Statement.NO_GENERATED_KEYS);
        fakeService.setCallResourceReturnValue(false);
        statement.getMoreResults();

        assertEquals(2, countMoreResultsInvocations(fakeService));
    }

    @Test
    void shouldResetMoreResultsStateAfterExecuteBatch() throws Exception {
        FakeStatementService fakeService = new FakeStatementService();
        Statement statement = new Statement(newConnection(fakeService), fakeService);
        exhaustMoreResults(statement, fakeService);

        fakeService.setCallResourceReturnValue(null);
        statement.executeBatch();
        fakeService.setCallResourceReturnValue(false);
        statement.getMoreResults();

        assertEquals(2, countMoreResultsInvocations(fakeService));
    }

    @Test
    void shouldResetMoreResultsStateAfterExecuteLargeBatch() throws Exception {
        FakeStatementService fakeService = new FakeStatementService();
        Statement statement = new Statement(newConnection(fakeService), fakeService);
        exhaustMoreResults(statement, fakeService);

        fakeService.setCallResourceReturnValue(null);
        statement.executeLargeBatch();
        fakeService.setCallResourceReturnValue(false);
        statement.getMoreResults();

        assertEquals(2, countMoreResultsInvocations(fakeService));
    }

    @Test
    void shouldResetMoreResultsStateAfterExecuteLargeUpdate() throws Exception {
        FakeStatementService fakeService = new FakeStatementService();
        Statement statement = new Statement(newConnection(fakeService), fakeService);
        exhaustMoreResults(statement, fakeService);

        fakeService.setCallResourceReturnValue(5L);
        statement.executeLargeUpdate("UPDATE t SET x = 1");
        fakeService.setCallResourceReturnValue(false);
        statement.getMoreResults();

        assertEquals(2, countMoreResultsInvocations(fakeService));
    }

    private static void exhaustMoreResults(Statement statement, FakeStatementService fakeService) throws Exception {
        fakeService.setCallResourceReturnValue(false);
        assertFalse(statement.getMoreResults());
        assertEquals(1, countMoreResultsInvocations(fakeService));
    }

    private static long countMoreResultsInvocations(FakeStatementService fakeService) {
        return fakeService.getCallResourceInvocations().stream()
                .filter(request -> "MoreResults".equals(request.getTarget().getResourceName()))
                .count();
    }

    private static Connection newConnection(FakeStatementService fakeService) {
        return new Connection(SESSION, fakeService, DbName.H2);
    }

    private static OpResult updateResult(int affectedRows) {
        return OpResult.newBuilder()
                .setSession(SESSION)
                .setType(ResultType.INTEGER)
                .setIntValue(affectedRows)
                .build();
    }

    private static java.util.Iterator<OpResult> emptyQueryResult() {
        OpResult result = OpResult.newBuilder()
                .setSession(SESSION)
                .setType(ResultType.RESULT_SET_DATA)
                .setQueryResult(OpQueryResultProto.newBuilder().build())
                .build();
        return Collections.singletonList(result).iterator();
    }
}
